***IMPORTING LIBRARIES***

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

Here, we import the necessary libraries. TensorFlow is the main deep learning library, and Keras is a high-level neural networks API that is now integrated into TensorFlow. The layers module from Keras provides building blocks for creating neural network layers.

***GENERATE SAMPLE DATA***

In [ ]:
import numpy as np
np.random.seed(42)
X = np.random.rand(100,1)
y = 3*X+2+0.1*np.random.randn(100,1)

Here, np.random.rand(100, 1) generates a 2D array (X) with 100 rows and 1 column. Each element in this array is a random number between 0 (inclusive) and 1 (exclusive). This array represents the input data.
This line generates the output data (y) based on a simple linear regression equation:

y=3X+2+noise.

3 * X: This represents the linear part of the equation, where the output is three times the input.

2: This is the intercept term, adding a constant value to each output.

0.1 * np.random.randn(100, 1): This part introduces some random noise. np.random.randn(100, 1) generates random numbers from a standard normal distribution (mean 0, standard deviation 1). Multiplying by 0.1 scales the noise to a smaller magnitude.

The overall effect is to create a dataset (X and y) that follows a linear relationship with some added random noise. This simulates a scenario where there is a true underlying linear relationship, but real-world data is often noisy due to various factors.

In summary, the generated data (X and y) is used to create a simple linear regression problem with known parameters (slope and intercept) and some added randomness to simulate a more realistic scenario.

In [ ]:
X

array([[0.37454012],
       [0.95071431],
       [0.73199394],
       [0.59865848],
       [0.15601864],
       [0.15599452],
       [0.05808361],
       [0.86617615],
       [0.60111501],
       [0.70807258],
       [0.02058449],
       [0.96990985],
       [0.83244264],
       [0.21233911],
       [0.18182497],
       [0.18340451],
       [0.30424224],
       [0.52475643],
       [0.43194502],
       [0.29122914],
       [0.61185289],
       [0.13949386],
       [0.29214465],
       [0.36636184],
       [0.45606998],
       [0.78517596],
       [0.19967378],
       [0.51423444],
       [0.59241457],
       [0.04645041],
       [0.60754485],
       [0.17052412],
       [0.06505159],
       [0.94888554],
       [0.96563203],
       [0.80839735],
       [0.30461377],
       [0.09767211],
       [0.68423303],
       [0.44015249],
       [0.12203823],
       [0.49517691],
       [0.03438852],
       [0.9093204 ],
       [0.25877998],
       [0.66252228],
       [0.31171108],
       [0.520

In [ ]:
y

array([[3.13232506],
       [4.82224218],
       [4.2051579 ],
       [3.59721856],
       [2.44608873],
       [2.50369482],
       [2.32204024],
       [4.54670142],
       [3.72249567],
       [4.07404203],
       [2.15329369],
       [4.94260467],
       [4.4443519 ],
       [2.68834408],
       [2.55518266],
       [2.64707803],
       [2.84252142],
       [3.54150308],
       [3.25662424],
       [2.72733593],
       [3.86517071],
       [2.44458711],
       [2.87694529],
       [3.07562682],
       [3.22667288],
       [4.31346335],
       [2.56474989],
       [3.46247559],
       [3.76111514],
       [2.17975632],
       [4.01125315],
       [2.52903015],
       [2.22090982],
       [4.83921202],
       [4.70501898],
       [4.42254066],
       [2.91986433],
       [2.53934055],
       [4.03346298],
       [3.35061222],
       [2.36264353],
       [3.36866293],
       [2.21744784],
       [4.80315451],
       [2.85544314],
       [3.89662811],
       [3.07541266],
       [3.420

***BUILIDING A SIMPLE NEURAL NETWORK***

In [ ]:
model = keras.Sequential([
    layers.Dense(units=1,input_dim=1)
])

We create a simple neural network model using the Sequential API in Keras. It consists of one dense (fully connected) layer with one neuron (output) and one input feature. The activation function defaults to linear in this case.

***COMPILING THE MODEL***


In [ ]:
model.compile(optimizer='sgd',
              loss='mean_squared_error')

We compile the model by specifying the optimizer and loss function. Here, we use Stochastic Gradient Descent (SGD) as the optimizer and Mean Squared Error (MSE) as the loss function. The choice of optimizer and loss function depends on the problem you are solving.
We compile the model by specifying the optimizer and loss function. Here, we use Stochastic Gradient Descent (SGD) as the optimizer and Mean Squared Error (MSE) as the loss function. The choice of optimizer and loss function depends on the problem you are solving

***TRAINING THE MODEL***

In [ ]:
model.fit(X,y, epochs=50,batch_size=32)

Epoch 1/50
4/4 [==============================] - 0s 4ms/step - loss: 8.3086
Epoch 2/50
4/4 [==============================] - 0s 4ms/step - loss: 6.7984
Epoch 3/50
4/4 [==============================] - 0s 4ms/step - loss: 5.5743
Epoch 4/50
4/4 [==============================] - 0s 5ms/step - loss: 4.5747
Epoch 5/50
4/4 [==============================] - 0s 7ms/step - loss: 3.7093
Epoch 6/50
4/4 [==============================] - 0s 4ms/step - loss: 3.0789
Epoch 7/50
4/4 [==============================] - 0s 4ms/step - loss: 2.5167
Epoch 8/50
4/4 [==============================] - 0s 3ms/step - loss: 2.0635
Epoch 9/50
4/4 [==============================] - 0s 4ms/step - loss: 1.6701
Epoch 10/50
4/4 [==============================] - 0s 4ms/step - loss: 1.3660
Epoch 11/50
4/4 [==============================] - 0s 4ms/step - loss: 1.1221
Epoch 12/50
4/4 [==============================] - 0s 4ms/step - loss: 0.9253
Epoch 13/50
4/4 [==============================] - 0s 5ms/step - loss: 0.

We train the model using the fit method. The input data (X) and target data (y) are provided, and the model is trained for 50 epochs with a batch size of 32. Training involves adjusting the model's weights to minimize the defined loss function.


In the context of training a machine learning model, the "batch size" refers to the number of training examples utilized in one iteration. During each iteration (also known as an epoch), the entire dataset is split into batches, and the model is trained on each batch sequentially.
The number of batches depends on the total size of your dataset and the chosen batch size. The formula to calculate the number of batches:
Nbatches= Nsamples/batchsize
Nsamples=is the total number of training samples in your dataset can be found by using len
Batchsize= is the number of examples in each batch





In [ ]:
len(X)

100

In [ ]:
batch_size=32

In [ ]:
num_batches=len(X)//batch_size
num_batches

3

***PREDICTING USING THE MODEL***

In [ ]:
predictions=model.predict(X)

4/4 [==============================] - 0s 3ms/step


We use the trained model to make predictions on the input data (X). The predict method takes input data and produces corresponding predictions.

***EVALUATING THE MODEL***

In [ ]:
mse=tf.keras.losses.mean_squared_error(y,predictions)
print(mse)

tf.Tensor(
[2.1988752e-03 5.5308014e-02 2.3263132e-02 1.6801117e-02 3.9674241e-02
 2.0027647e-02 7.0448876e-03 2.7622335e-02 1.0700879e-04 6.3771964e-03
 2.5938280e-02 9.5256001e-02 2.1396667e-02 8.9386906e-03 2.3453780e-02
 4.2393701e-03 2.7200995e-02 2.2648779e-05 3.9512012e-03 6.1660741e-02
 1.1255811e-02 2.5698770e-02 1.0189603e-02 6.9902032e-03 2.3030477e-02
 1.7129792e-02 3.5040744e-02 3.3728939e-03 2.4536490e-03 3.9121978e-02
 6.9012582e-02 2.3008628e-02 4.0840473e-02 6.5851100e-02 6.6427249e-03
 3.3568837e-02 7.8308191e-03 1.3420651e-03 9.5118927e-03 1.2265079e-04
 3.9840247e-02 1.1093051e-02 1.7063890e-02 1.0063653e-01 1.6745260e-03
 1.8887450e-04 2.4715380e-03 1.3176134e-02 9.7834896e-03 3.3498097e-03
 3.1161621e-02 1.2260326e-02 7.2253577e-02 3.3718221e-02 7.4564400e-03
 6.5475732e-02 1.0305989e-01 1.1581038e-02 1.0944256e-01 5.1852055e-03
 1.5889684e-02 2.1093154e-02 7.7585667e-02 3.5563421e-02 7.2161327e-03
 2.8461695e-02 1.1996935e-01 4.0353753e-02 3.8639829e-02 1.3205366